server:
  port: 9090   # 원하는 포트 번호
  error:
    whitelabel:
      enabled: false   # 기본 Whitelabel Error Page 비활성화
    path: /error       # 에러 시 보여줄 경로
logging:
  file:
    name: logs/spring-boot.log
  level:
    root: INFO
    com.chihyunglee: DEBUG
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/   # JSP 등 뷰 파일 위치
      suffix: .jsp              # 뷰 파일 확장자
  mail:
    host: smtp.gmail.com
    port: 587
    username: eno7135@gmail.com
    password: vnzbrqsjlirrtyaj   # 구글 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  
  datasource:
    url: jdbc:mysql://localhost:3306/mydb   # DB URL
    username: myuser                        # DB 계정
    password: mypassword                    # DB 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver